version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    cooldown:
      default-days: 3
      semver-major-days: 14
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      production-minor-patch:
        applies-to: "version-updates"
        dependency-type: "production"
        update-types:
          - "minor"
          - "patch"
      development-minor-patch:
        applies-to: "version-updates"
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
      include: "scope"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:20"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 3
    cooldown:
      default-days: 3
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      minor-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "chore"
      include: "scope"
